<a href="https://colab.research.google.com/github/lavillegas/pythonfinanzaseafit/blob/master/Clase_1_diligenciada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<p><img alt="Colaboratory logo" height="140px" src="https://upload.wikimedia.org/wikipedia/commons/b/bf/EAFIT-2015.png" align="left" hspace="10px" vspace="0px"></p>

<h1> Diplomado Python para Finanzas</h1>




<p><a name="contents"></a></p>

# Contenido Clase 1

- <a href="#colabIntro">1. Introducción al Colaboratory de Google</a><br>
- <a href="#pythonIntro">2. Introducción a Python</a><br>



<p><a name="colabIntro"></a></p>

# 1) Introducción a Google Colaboratory

[[Contenidos]](#contents)

Este documento es un [Notebook de Jupyter](https://jupyter.org/), almacenado en el Colaboratory de Google. En lugar de una página estatica se trata de un ambiente interactivo en el cual puede ejecutar scripts en Python.

A continuación se muestra una **celda de código** con un  script de Python que calcula un value, lo almacena en una variable y lo imprime en pantalla:

In [3]:
# A continuación se realiza un cálculo sencillo del area de un cuadrado de lado 5 y se almacena dicho cálculo en 
# la variable area, luego se imprime en pantalla

area=20000*0.5

print(area)

10000.0


Para ejecutar código en colab, se debe seleccionar la celda haciendo click  y lurgo  se debe hacer click el botón "play" a la izquierda de la celda; también puede usar el keyboard shortcut  "Shift/Ctrl+Enter".

Todas las variables son almacenadas de forma global (mas adelante ahondaremos en este concepto), de tal manera que se puede usar y modificar en celdas diferentes. En los dos siguientes ejemplos se muestran modificaciones ejecutadas sobre la variable área

In [ ]:
print("Valor de la variable inicial",area)

#Primera  modificación  de la variable area

area=area/2;

print("Valor de la variable modificado", area)

Valor de la variable inicial 25
Valor de la variable modificado 12.5


<p><a name="pythonIntro"></a></p>

# 2) Introducción a Python

[[Contenidos]](#contents)

El objetivo de la presente sección es el de suministrar al lector una breve introducción al lenguaje Python, y ayudar a los principiantes a familiarizarse con dicho lenguaje.

<p><a name="sections"></a></p>

#Secciones

- <a href="#whatwhy">2.1. ¿Qué, cómo, por qué y cuando Python?</a><br>
- <a href="#mods">2.1. Módulos</a><br>
- <a href="#ayuda">2.2. Ayudas y descripciones</a><br>
- <a href="#vars">2.3. Elementos Básicos de Python</a><br>
 - <a href="#syms">2.3.1. Nombres de variables</a><br>
  - <a href="#asign">2.3.2. Asignación</a><br>
  - <a href="#ftypes">2.3.3. Tipos de variables</a><br>
 - <a href="#mscut">2.3.4. Atajos de operaciones matemáticas y asignaciones</a><br>
- <a href="#sltd">2.4. Strings, Listas y diccionarios</a><br>
 - <a href="#strings">2.4.1. Strings</a><br>
 - <a href="#strings">2.4.1.1 Ejercicios de práctica</a><br>
 - <a href="#alist">2.4.2. List</a><br>
 - <a href="#alist">2.4.2. Ejercicios de práctica</a><br>
 - <a href="#tuples">2.4.3. Tuplas</a><br>
 - <a href="#diccionarios">2.4.4. Diccionarios</a><br>
  - <a href="#diccionarios">2.4.4.1 Ejercicios de práctica</a><br>
 - <a href="#cond">2.5. Condicionales: if, elif, else </a><br>
- <a href="#iter">2.7. Iteraciones y ciclos lógicos </a><br>
 - <a href="#cicl">2.7.1 Ciclos for y while </a><br>
 - <a href="#contr">2.7.2 Sentencias de control de bucles</a><br>
- <a href="#func">2.8. Funciones y clases </a><br>
 - <a href="#funci">2.8.1. Funciones</a><br>
 - <a href="#funci">2.8.1.1 Ejercicios de práctica</a><br>
 - <a href="#class">2.8.2. Programación Orientada a Objetos (Clases) </a><br>
- <a href="#inout">2.9. Archivos de entrada y salida (I/O) </a><br>
 - <a href="#lecte">2.9.1. Lectura de entrada de teclado </a><br>
 - <a href="#apyci">2.9.2. Apertura y cierre de archivos</a><br>
 - <a href="#leyes">2.9.3. Leer y escribir archivos </a><br>
 - <a href="#subar">2.9.4. Subir y leer archivos </a><br>
 - <a href="#des">2.9.9. Descargar archivos en el sistema local </a><br>
 - <a href="#goodr">2.9.7. Google drive: Paquete Pydrive </a><br>
 - <a href="#git">2.10.7. Github </a><br>

 - <a href="#numpy">3.0. Numpy </a><br>

<p><a name="whatwhy"></a></p>

##2.1. ¿Qué, cómo, por qué y cuándo Python?
[[Secciones]](#sections)
- <b>Popularidad:</b> En palabras de la revista The Economist: <em>"Python is becoming the world’s most popular coding language"</em>
<br>
<p><img alt="economist  logo" width="700" height="600" src="https://www.economist.com/img/b/1280/1401/90/sites/default/files/20180728_WOC883.png" align="center" hspace="10px" vspace="0px"></p>
<br>
-<b>Lenguaje de alto nivel:</b> Facilita la lectura humana por encima de la lectura de máquina. Fácil de usar y fácil de aprender

<br> 
<p><img alt="comparison  logo" width="600" height="200" src="https://belitsoft.com/images/uploads/blog/Hello%20world%20JAva%20%2B%20Python.png" align="center" hspace="10px" vspace="0px"></p>


<br> 

<p><b>Aspectos técnicos de Python </b></p>
<ul> Lenguaje de programación de propósito general que puede ser utilizado efectivamente para construir  programas que no requieran acceso directo al hardware</ul>
<ul> Lenguaje de programación orientado a objetos </ul>
<ul> Amplia disponibilidad de librerias </ul>
<ul> Código Open Source </ul>
 




<p><a name="mods"></a></p>

##2.1. Módulos

[[Secciones]](#sections)

La mayoria de funcionalidades en Python estan proporcionadas por los módulos. Para poder usar un módulo en un programa de Python debe importarse mediante la sentencia **import**. Por ejemplo, para importa el módulo *math*, el cual contiene gran variedad de funciones matemáticas, podemos hacer lo siguiente

In [4]:
import math

La línea de código anterior implica la importación de todo el módulo, haciéndolo disponible para su uso posterior dentro del programa. Por ejemplo, podemos usar funciones triconométricas para calcular algún valor y almacenarlo en una variable:

In [5]:
# Calculemos el coseno de 2 * pi
x = math.cos(2*math.pi)
x

1.0

En lugar podemos escoger importar unas cuantas funciones del módulo haciendo explicito cuales de ellas queremos importar, permitiendo al usuario tener claridad de los compromisos del programa. Por ejemplo, podemos elegir importar solo las funciones $cos$ y el valor de $\pi$:

In [ ]:
from math import cos, pi

x = cos(3*pi)
x

-1.0

También es posible asignarle un nombre corto o de acceso a los modulos 

In [6]:
import numpy as np
from math import pi as number_pi

#A continuación, convertímos el número pi de radianes a grados.

x = np.rad2deg(number_pi)
x

180.0

<p><a name="ayuda"></a></p>

## 2.2. Ayudas y descripciones

[[Secciones]](#sections)

Mediante el uso de la función **help**, se puede obtener una descripción de casi todas las funciones. 

In [ ]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x[, base])
    
    Return the logarithm of x to the given base.
    If the base not specified, returns the natural logarithm (base e) of x.



Tambien puede obtener la ayuda poniendo el sígno interrogante (?) al final de la expresión, así:

In [7]:
math.log?

<p><a name="vars"></a></p>

## 2.3. Elementos Básicos de Python

[[Secciones]](#sections)


<p><a name="syms"></a></p>

### 2.3.1. Variables y tipos

Los nombres de las variables en Python pueden contener caracteres alfanuméricos *a-z*, *A-Z*, *0-9* y algunos caracteres especiales como _. Los nombres de las variables deben comenzar con una letra y no con un numero.

Por convención, los nombres de las **variables** comienzan con letras minúsculas, y los nombres de las **Clases** con letras mayúsculas.

Adicionalmente, existe un número de palabras reservadas conocidas como **keywords** que no pueden ser usadas como nombres de variables. Estas palabras claves son:

> `and, as, assert, break, class, continue, def, del, elif, else, except, exec, finally, for, from, global, if, import, in, is, lambda, not, or, pass, print, raise, return, try, while, with, yield`



<p><a name="asign"></a></p>

### 2.3.2. Asignación.

En Python, el operado de asignación es "=".  Python es un lenguaje de tipado dinámico, de tal forma que no es necesario asignarle un tipo a la variable cuando es creada.

La asignación de un valor a una variable crea la variable. Por ejemplo:

In [ ]:
# asignación de el valor 1 a la variable x

x = 1.0

Aunque no se hizo explicito, la variable tiene un tipo asociado a ella. El tipo de la variable puede deducirse del valor que le fue asignado. También se puede consultar el tipo mediante la función `type`:

In [ ]:
type(x)

int

Si asignamos a la variable un nuevo valor, su tipo puede cambiar:

In [ ]:
x = 1
type(x)

int

Si intentamos usar una variable que no ha sido definida aun, obtenemos un error `NameError` (Nótese que usarémos en los notebooks los bloques `try/except` para tratar las excepciones, de tal forma que el notebook no se interrumpa). 

En el siguiente código, intentaremos usar la función `print` de tal forma que si ocurre la excepción `NameError`, se imprime un mensaje en pantalla; de lo contrario, se generará un error. Más adelante, en el presente notebook, se estudiará mas detalladamente el manejo de excepciones.

 

In [ ]:
try:
    print(y)
except(NameError) as err:
    print("NameError", err)
else:
    raise

NameError name 'y' is not defined


<p><a name="ftypes"></a></p>

### 2.3.3. Tipos de variables.

En Python, los tipos pueden ser  escalares (scalar) o no-escalares (non-scalar). Consideremos los objetos escalares como la unidad no divisible (atomos) del lenguaje. 
Python tiene 4 tipos de objetos escalares





1.   Enteros **(int)**: Utilizados para denotar numeros enteros
2.   Punto flotante **(float)**: Utilizados para representar numeros reales, traen consigo siempre un punto decimal  (ejm: 3.0, 5.734, -14.21)
3.   Buleanos **(boolean)**: Utilizados para denotar **True** or **False** (Verdadero o Falso)
4.   **None**:  Es un tipo con un unico valor (Ninguno)

Veamos algunos ejemplos de estos tipos:






In [ ]:
# integers, int, enteros

x = 3
type(x)

int

In [ ]:
# float, flotante, reales

x = 13.0
type(x)

float

In [ ]:
# boolean

v1 = True
v2 = False

type(v1), type(v2)

(bool, bool)

**Operadoros para los tipos float e int**
+ **i+j**: La suma de i y j. Si ambos son int el resultado es int, si al menos uno es float el resultado sera float
+ **i-j**:La resta de i y j. Si ambos son int el resultado es int, si al menos uno es float el resultado sera float
+ **i*j**:El producto de i y j. Si ambos son int el resultado es int, si al menos uno es float el resultado sera float
+ **i//j**: Division entera, ejemplo, 6//4 da como resultado el int 1.
+ **i/j**:Division flotante, en python 3 este resultado siempre sera float
+ **i%j**: conocido como operador modulo, retorna el residuo del int i dividido el int j. "i mod j"
+  i**j : i elevado a la j
+ Operadores de comparación: == (igual), != (no igual), > (mayor que). < (menor que), >= (al menos), <= (a lo sumo)

In [ ]:
# Algunas operaciones basicas
[1 + 4, 1 - 3.5, 14.0* 2, 5 % 3]

[5, -2.5, 28.0, 2]

In [ ]:
print(6/2)
print(1/2.0)
print(36//6)

3.0
0.5
6


In [ ]:
# Potenciacion
print(2**2)
print(3**3.0)
print(4**4.4)

4
27.0
445.7218884076158



*   Los booleanos pueden estar conectados o precedidos por palabras como `and`, `not`, `or`. ( Si, Y , No, O)

<p><img alt="verdad  logo" width="440" height="200" src="https://www.researchgate.net/profile/Marcen_Laguna/publication/327702158/figure/fig3/AS:671885788475392@1537201463034/Figura-3-Tablas-de-verdad-5.ppm" align="center" hspace="10px" vspace="0px"></p>



In [ ]:
True and False

False

In [ ]:
False or False

False

In [ ]:
not False

True

In [ ]:
True or False

True

In [ ]:
3>1,4<1

(True, False)

In [ ]:
2>3,2<2

(False, False)

In [ ]:
6<=6,4>=3

(True, True)

In [ ]:

[3,2]==[3,2]

True

In [ ]:

2 != 5

True

<p><a name="mscut"></a></p>

### 2.3.4 Atajos de operaciones matemáticas y asignaciones.

[[Secciones]](#sections)

Por ejemplo, la siguiente asignación y operación:



In [ ]:
x = 1
x = x+1
print(x)

2


<p><img alt="verdad  logo" width="340" height="300" src="https://i.redd.it/uq7asmzqj3j51.png" align="center" hspace="10px" vspace="0px"></p>


el comando `x = x + 1`, puede ser abreviado como `x += 1`. Este tipo de abreviaciones funcionan con las siguientes operaciones `+=`, `-=`, `/=` , y `*=`.

In [8]:
x = 1
x *= 1
print(x)

1


<p><a name="sltd"></a></p>

## 2.4. Strings, listas y diccionarios.

[[Secciones]](#sections)

Los strings, las listas y los diccionarios son ejemplos de **estructuras de datos**.  Una estructura de datos es un formato de almacenamiento, organizacion y gestión que permiten el acceso eficiente y tambien la modificacion de datos.  En otras palabras, una estructura de datos es la coleccion de **valores**, las **relaciones** entre ellos y las distintas **funciones y operaciones** que pueden aplicarse a ellos.

<p><a name="strings"></a></p>

###2.4.1 Strings
En Python, un string (cadena) es la secuencia de caracteres introducida dentro de ya sean comillas o dobles o simples.
Los string suelen utilizarse para guardar mensajes, palabras, etc..

In [9]:
s = "Hola mundo"
type(s)

str

In [ ]:
# La funcion len nos permite conocer la longitud del string, es decir
# el número de caracteres en el string
len(s)

10

In [ ]:
# Reemplazo de un substring dentro de un string
s2 = s.replace("mundo","alumnos")
print(s2)

Hola alumnos


Podemos indexar los caracteres en un string mediante el uso de `[]` 
**Se debe tener cuidado ya que la indexación en Python empieza en 0.**

In [ ]:
s[0],s[1],s[2]

('H', 'o', 'l')

In [ ]:
s[0:4]

'Hola'

Si omitimos en el intervalo el `start` o el `stop`, se toma por defecto el princio y el final de string, respectivamente

In [ ]:
s[:4]

'Hola'

In [ ]:
s[5:]

'mundo'

In [ ]:
s[:]

'Hola mundo'

También podemos definir el tamaño del step (paso) usando la sintaxis `[start:end:step]`(el valor por defecto del paso es 1)

In [ ]:
s[::1]

'Hola mundo'

In [ ]:
s[::3]

'Hauo'

A esta técnica se le conoce con el nombre de **slicing**.

**Ejemplos de formatos de strings**

In [ ]:
#Contatenación de strings con +
print("Común"+"mente")

Comúnmente


In [ ]:
type("s")

str

In [ ]:
#La función print puede concatenar dependiendo de como se introduzcan las entradas.


print("Propia" "mente")
print("Común","mente")
print(("Mega","mente"))

Propiamente
Común mente
('Mega', 'mente')


In [ ]:
# La función print convierte todos las entradas a strings
print("Común", 1.0, False)

Común 1.0 False


In [ ]:
print("Las líneas nuevas son indicadas por \nlos espacios por \t.")



Las líneas nuevas son indicadas por 
los espacios por 	.


In [ ]:
strString = """String
con varias
líneas de texto."""
print(strString)


String
con varias
líneas de texto.


**CHEATSHEET METODOS DE STRINGS**

**Cases I**
- **s.capitalize()** Mayuscula al principio: 'hello' => 'Hello'

- **s.lower()** todo en minúscula: 'HELLO' => 'hello'
- **s.swapcase()** Cambia todas los caracteres # 'Hello' => "hELLO"
- **s.title()** Mayúsculas primeras letras # 'hello world' => 'Hello World'
- **s.upper()** Todo Mayúscula # 'hello' => 'HELLO'

**Operaciones secuenciales I**

- **a in b** retorna true si b contiene a
- **a + b** Concatena a y b
- **len(s)** longitud de s
- **min(s)** Caracter mas pequeño de s
- **max(s)** Caracter mas grande de s

**Operaciones secuenciales II**

- **a not in b** retorna true si a no esta contenido en b
- **s * n** (int) Retorna n copias de s concatenadas # 'hello' => 'hellohellohello'
- **s[i:j:k]** Slices (rebanadas)  de s desde i hasta j con pasos de dimension k
- **a.count(b)** Conteo de b en a

**Whitespace I**
**s.strip()** Remueve espacios en blanco al inicio y al final # ' hello ' => 'hello

**Encontrar / Reemplazar I**
- **a.index(b, i, j)** Index de primera ocurrencia de b en a luego del index i pero antes del index j
- **a.find(b)** Encuentra y recupera el  index mas bajo de b en a

- **a.replace(b, c)** Reemplaza b con c en s
- **a.replace(b, c, n )** Reemplaza b con c en a n veces

**Cases II**


- **s.islower()** Retorna  true si s esta en minuscula

- **s.isupper()** Retorna  true si s esta en mayuscula

**Inspección I**

- **a.endswith(b)** Retorna true si a termina con b
- **s.isalnum()** Retorna true si s es alfanumerico
- **s.isalpha()** Retorna true si s is alfabetico
- **s.isdecimal()** Retorna true si s is decimal
- **s.isnumeric()** Retorna true si s is numerico
- **a.startswith(b)** Retorna true si a empieza con b

**Splitting I**

- **s.join('123')** Retorna s unido al objeto  iterable '123' # 'hello' => '1hello2hello3'
- **s.split(sep, maxsplit)** Retorna lista de s partido por sep con la maxima cantidad de maxsplits llevados a cabo
-  **s.splitlines()** Retorna una lista de lineas  en s # 'hello\nworld' => ['hello', 'world']

**Inspección II**

- **s[i:j]**: Slice (Rebanada)  de s desde i hasta j
- **s.isdigit()** Retorna  true si s es  digito
- **s.lstrip()** Remueve  espacios en blancos precedentes de s # ' hello ' => 'hello '
- **s.rstrip()** Remueve espacios en blanco de s # ' hello ' => ' hello'


<p><a name="stringsexercises"></a></p>

###2.4.1.1 Ejercicios de práctica

**Ejercicio 1: Dificultad Zero**

Cuente el numero de letras que contiene su primer nombre, ejemplo: Juan deberia retornar 4

In [11]:
#Desarrolle aqui el ejercicio
n="Luis"
len(n)

4

De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

nombre="Juan"
print("Mi nombre tiene ", len(nombre)," letras")

--->

**Ejercicio 2: Dificultad Rookie**

Considere el **string1** tal que 

**string1**="Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Macondo era entonces una aldea de veinte casas de barro y cañabrava construidas a la orilla de un río de aguas diáfanas que se precipitaban por un lecho de piedras pulidas, blancas y enormes como huevos prehistóricos. El mundo era tan reciente, que muchas cosas carecían de nombre, y para mencionarlas había que señalarlas con el dedo."

Encuentre e imprima:

- Primera ocurrencia de la letra "a"
- Numero de veces que aparece la letra "a"
- imprima los primeros 5 caracteres
- imprima los siguientes 5 caracteres
- Imprima el  13avo caracter
- Imprima los caracteres con posicionamiento impar
- Imprima los ultimos 5 caracteres
- Convierta todo a mayuscula
- Convierta todo a minuscula


In [29]:
# Desarolle aqui el ejercicio
string1="Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Macondo era entonces una aldea de veinte casas de barro y cañabrava construidas a la orilla de un río de aguas diáfanas que se precipitaban por un lecho de piedras pulidas, blancas y enormes como huevos prehistóricos. El mundo era tan reciente, que muchas cosas carecían de nombre, y para mencionarlas había que señalarlas con el dedo."
# Primera ocurrencia
a=string1.index("a")
a
# Conteo de ocurrencias
b=string1.count("a")
b
# primeros 5 caracteres
string1[0:5]
# siguientes 5 caracteres
string1[5:10]
# el caracter 13
string1[12:13]
# los caracteres impares
string1[::2]
# ultimos 5 caracteres
string1[-5:]
# todo en mayuscula
c=string1.upper()
c
# todo en minuscula
d=string1.lower()
d


De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(
s="Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Macondo era entonces una aldea de veinte casas de barro y cañabrava construidas a la orilla de un río de aguas diáfanas que se precipitaban por un lecho de piedras pulidas, blancas y enormes como huevos prehistóricos. El mundo era tan reciente, que muchas cosas carecían de nombre, y para mencionarlas había que señalarlas con el dedo."


# Primera ocurrencia de la letra "a"
print(s.index("a"))

# Numero de veces que aparece la letra "a"
print("a occurre %d times" % s.count("a"))

# Slicing de nuestra frase
# imprima los primeros 5 caracteres
print("los primeros 5 caracteres son '%s'" % s[:5]) # Start to 5
# imprima los siguientes 5 caracteres
print("los siguientes 5 caracteres son '%s'" % s[5:10]) # 5 to 10
# Imprima el  13avo caracter
print("El  13avo caracter es '%s'" % s[12]) 
#Imprima los caracteres con posicionamiento impar
print("Los caracteres con posicionamiento impar son '%s'" %s[1::2]) 
#imprima los ultimos 5 caracteres
print("Los ultimos 5 caracteres son '%s'" % s[-5:]) # 

# Convierta todo a mayuscula
print("String en uppercase: %s" % s.upper())

# Convierta todo a minuscula
print("String en lowercase: %s" % s.lower())

--->

**Ejercicio 3: Dificultad Hero**

Reorganice el string "AdoROprogRAmarenPyTHON" de tal manera que todas las letras en minuscula queden de primeras. Es decir, si el string fuses TaCo, el resultado sería aoTC

In [25]:
# Desarrolle aqui el ejercicio
string2="AdoROprogRAmarenPyTHON"
string2_l=""
string2_u=""

for x in string1:
  string2

'AdoROprogRAmarenPyTHON'

De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

string1 = "AdoROprogRAmarenPyTHON"
lower = []
upper = []
for char in string1:
    if char.islower():
        lower.append(char)
    else:
        upper.append(char)
string_ordenado = ''.join(lower + upper)
print("Reorganizando caracteres dando  precedencia a las letras en minuscula:")
print(string_ordenado)

--->

<p><a name="alist"></a></p>

### 2.4.2. Listas

[[Secciones]](#sections)

Una lista es una  secuencia de datos llamados items o elementos. Los elementos pueden ser de cualquier tipo. Algunos ejemplos de listas en la vida real son:
- Lista de compras
- Lista de pendientes
- Lista de invitados
- Una receta de cocina


Las listas son muy similares a los `strings` sin embargo los elementos de una lista pueden ser de cualquier tipo. Además, las listas son **mutables**. En cualquier momento de su vida, pueden insertarse elementos, removerse elementos,
o reemplazarlos. La identidad de la lista se mantiene pero su estado, su longitud y su contenido puede variar.

La sintaxis en Python es de la forma `[...]`.

In [ ]:
l=[0,1,2,3]
print(type(l))
print(l)

<class 'list'>
[0, 1, 2, 3]


In [ ]:
[1951,1969,1984] # Una lista de integers
['apples','oranges','cherries'] # Una lista de strings

['apples', 'oranges', 'cherries']

Veamos un claro ejemplo de la mutabilidad de las listas
sea a=["perro" , "gato", "loro"] y b=a

In [ ]:
a=["perro","gato","loro"]
b=a
print("Esta es la lista b",b)
b[0]="rana"
print("Esta es la lista a",a)

Esta es la lista b ['perro', 'gato', 'loro']
Esta es la lista a ['rana', 'gato', 'loro']


Para evitar este tipo de situaciones que podrian generar errores en nuestros programas hacemos uso del metodo **.copy()**

In [ ]:
a=["perro","gato","loro"]
b=a.copy()
print("Esta es la lista b",b)
b[0]="rana"
print("Esta es la lista a",a)

Esta es la lista b ['perro', 'gato', 'loro']
Esta es la lista a ['perro', 'gato', 'loro']


Podemos usar las mismas técnicas de *slicing* que usamos en los *strings*

In [ ]:
l=[0,1,2,3,4]
print(l[:])
print(l[0:2])
print(l[::2])

[0, 1, 2, 3, 4]
[0, 1]
[0, 2, 4]


Los elementos de una lista no tiene que ser todos del mismo tipo

In [ ]:
l = [1, 'a', 1.0]

Las listas en Python pueden ser anidadas arbitrariamente:


In [ ]:
nested_list = [1, [2, [3, [4, [5]]]]]
nested_list

[1, [2, [3, [4, [5]]]]]

Las listas desempeñan un papel muy importante en Python y, por ejemplo, se utilizan en bucles y otras estructuras de control de flujo. Hay una serie de funciones convenientes para generar listas de varios tipos

In [ ]:
inicio = 1
final = 24
paso = 3

list(range(inicio, final, paso))

[1, 4, 7, 10, 13, 16, 19, 22]

In [ ]:
# Convertir un string en una lista  mediante list
s="Hola mundo"
print(s)

s2 = list(s)

s2

Hola mundo


['H', 'o', 'l', 'a', ' ', 'm', 'u', 'n', 'd', 'o']

In [ ]:
# Ordenar una lista
s2.sort()

print(s2)

[' ', 'H', 'a', 'd', 'l', 'm', 'n', 'o', 'o', 'u']


***Adición, inserción, modificación y remoción de elementos de una lista***


In [ ]:
# Creación de una lista vacía
l = []

# Adición de elementos usando `append`
l.append("A")
l.append("d")
l.append("d")

print(l)

['A', 'd', 'd']


Podemos modificar una lista al asignar nuevos valores a elementos de esa lista.



In [ ]:
l[1] = "s"
l[2] = "m"

print(l)

['A', 'p', 't']


In [ ]:
l[1:3] = ["k", "j"]

print(l)

['A', 's', 'm']


Inserción de elementos mediante `insert`.


In [ ]:
l.insert(0, "i")
l.insert(1, "n")
l.insert(2, "s")
l.insert(3, "e")
l.insert(4, "r")
l.insert(5, "t")

print(l)

['i', 'n', 's', 'e', 'r', 't', 'i', 'n', 'e', 'r', 't', 'm']


Remoción del primer elemento de un valor específico mendiante `remove`



In [ ]:
#l.remove("A")
ls=[l.remove(x) for x in l if x=="s"]
print(l)

['i', 'n', 'e', 'r', 't', 'i', 'n', 'e', 'r', 't', 'm']


Remoción de un elemento en una posición específica usando `del`



In [ ]:
del l[7]
del l[6]

print(l)

['i', 'n', 's', 'e', 'r', 't']


La concatenacion y las comparaciones tambien puede ser utilizadas en listas


In [ ]:
first=[1,2,3]
second=first+[5,6]
print(second)
first==second

[1, 2, 3, 5, 6]


False

Finalmente, el operador **in** puede ser utilizado para detectar la presencia o ausencia de un elemento:

In [ ]:
3 in [1, 2,3]

True

Abordemos un poco el concepto de **Lists Comprehension**, que no es otra cosa que una forma abreviada de aplicar transformaciones a un iterable como lo son las listas

In [ ]:
# Supongamos que queremos recuperar una lista con los valores de
List = [1, 2, 3, 4, 5, 6, 7]
# elevados al cuadrado, para eso usamos
List_cuad=[x*x for x in List]
print(List_cuad)

[1, 4, 9, 16, 25, 36, 49]


**CHEATSHEET METODOS DE LISTAS**

- **a.append(b)**: agrega **b** al final de una lista
- **a.count(b)**: cuenta la cantidad de veces que aparece **b** en la lista
- **a.extend([L])**:extiende una lista agregando un iterable  **L** al final (otra lista, o un range)
- **a.index(b)**: devuelve el index de la primera apariciÓn de **b**
- **a.insert(n,b)**: Inserta el elemento **b** en la posiciÓn n 
- **a.pop()**: devuelve el último elemento de la lista, y lo borra de la lista
- **a.remove(b)**:  borra la primera aparición de **b** en la lista
- **a.reverse()**:  invierte el orden de los elementos de una lista
- **a.sort()**: ordena los elementos de una lista

<p><a name="stringsexercises"></a></p>

###2.4.2.1 Ejercicios de práctica

**Ejercicio 1: Dificultad Zero**

Para la lista c=[1,2,3,4,5,6,7] generere una lista **d** cuyos elementos sean la raiz cuadrada de los elementos de **c**

In [30]:
#Desarrolle aqui el ejercicio
c=[1,2,3,4,5,6,7]
d=[math.sqrt(x) for x in c]
d

[1.0,
 1.4142135623730951,
 1.7320508075688772,
 2.0,
 2.23606797749979,
 2.449489742783178,
 2.6457513110645907]

De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

c=[1,2,3,4,5,6,7]
d=[x**0.5 for x in c]
print(d)

--->

**Ejercicio 2: Dificultad Rookie**

Concatene las siguientes listas 
- a=["Esta "]
- b=["sesion","metodologia"]

en una sola de esta forma
- c=["Esta sesion","Esta metodologia"]

In [32]:
#Desarrolle aqui el ejercicio
a=["Esta "]
b=["sesion","metodologia"]
c=[a[0]+b[0],a[0]+b[1]]
c

['Esta sesion', 'Esta metodologia']

De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

a=["Esta "]
b=["sesion","metodologia"]
c = [x+y for x in a for y in b]
print(c)

--->

**Ejercicio 3: Dificultad Hero**
Dada la siguiente lista, remueva todos los numeros que sean multiplos de 3
- a=[1,33,45,26,11,107,100,44,63,99,283245372]

In [ ]:
#Desarrolle aqui el ejercicio
a=[1,33,45,26,11,107,100,44,63,99,283245372]
b=[n for n in a if n%3 != 0]
print(b)

[1, 26, 11, 107, 100, 44]


De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

a=[1,33,45,26,11,107,100,44,63,99,283245372]
b=[n for n in a if n%3 != 0]
print(b)

--->

**Ejercicio 4: Dificultad Leyenda**
Dadas las siguientes listas representando matrices cuadradas, retorne para cada una de ellas el valor de la suma de los elementos en sus diagonales

- a = [[1,22,44,8],[4,15,6,12],[7,5,9,34],[11,22,33,22]]
 
- b = [[-5,0,5],[3,3,0],[0,1,0]]
 

 


In [69]:
#Desarrolle aqui el ejercicio
a = [[1,22,44,8],[4,15,6,12],[7,5,9,34],[11,22,33,22]]
 
b = [[-5,0,5],[3,3,0],[0,1,0]]
 
i=0
sum_a=0
sum_b=0

for x in a:
  sum_a +=  a[i][i]
  if i <= 2:
    sum_b += b[i][i]
    i = i + 1
  else:
    i = i + 1

print(sum_a)
print(sum_b)

47
-2


De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

Oops los ejercicios de dificultad leyenda no tienen codigo, solo la solución correcta
suma_diagonal(a)=47
suma_diagonal(b)=-2

--->

<p><a name="tuples"></a></p>

### 2.4.3. Tuplas

[[Secciones]](#sections)

Las tuplas son como las listas, excepto que estas no pueden ser modificadas una vez se han creado, es decir, son inmutables.

En Python, las tuplas son creadas usando la sintaxis (..., ..., ...), incluso ..., ...:

In [ ]:
point = (10, 20)

print(type(point))
print(point)

<class 'tuple'>
(10, 20)


In [ ]:
# otro ejemplo de tupla
tupla = None, 54321, 'hola!'
print(tupla)

(None, 54321, 'hola!')


Si intentamos asignar un nuevo valos a un elemento de la tupla, obtenemos un error:



In [ ]:
try:
    point[0] = 20
except(TypeError) as er:
    print("TypeError:", er)
else:
    raise


TypeError: 'tuple' object does not support item assignment


**CHEATSHEET METODOS DE STRINGS**

- a.count(b): Cuenta las veces que aparece b en la tupla a
- a.index(b): Devuelve el index de la  primera aparición de b  en la tupla.


<p><a name="diccionarios"></a></p>

### 2.4.4. Diccionarios

[[Secciones]](#sections)

Como vimos, las listas organizan sus elementos por posición. Esta forma de organizacion es útil cuando queremos ubicar el primer, último o cada uno de los elementos de una secuencia 
Sin embargo, la posición de un dato puede ser irrelevante en algunos casos y solemos estar mas interesados en su asociación con otro elemento de la estrucutrua de datos
Es ahí que se utlizan los **diccionarios**, los cuales organizan su información por asociación y no por posición.

Los diccionarios son parecidos a las listas, excepto que cada elemento es una pareja key-value. La sintaxis en los diccionarios es de la forma {key1 : value1, ...}:



In [ ]:
info={'Name':'Molly', 'Age':18}

print(type(info))
print(info)

<class 'dict'>
{'Name': 'Molly', 'Age': 18}


A las entradas de los diccionarios solo puede accederse mediante el nombre de la key.


In [ ]:
info["Name"]

'Molly'

In [ ]:
info["Name"] = "John"
info["Age"] = 14

# podemos agregar una nueva entrada
info["Lastname"] = "White"

print(info)

#Los diccionarios vacios pueden generarse como
d={}
d=dict()

{'Name': 'John', 'Age': 14, 'Lastname': 'White'}


**CHEATSHEET METODOS DE DICCIONARIOS**
- **d.clear()**:  remueve todos los elementos
- **d.copy()**:  devuelve una copia  superficial (shallow) del tipo diccionario.
- **dict.fromkeys(L)**: crea un nuevo diccionario con claves a partir de la secuencia L.
- **d.get('key')**: devuelve el valor en base a una coincidencia de búsqueda, de lo contrario devuelve el objeto None
- **d.has_key('key')**: devuelve una lista de pares de diccionarios (key, value), como 2-tupla.
- **d.items()**: devuelve un iterador sobre los valores del diccionario
- **d.keys()**: devuelve una lista con las keys del diccionario
- **d.pop('key')**: remueve específicamente una key del diccionario y devuelve valor correspondiente
- **d.popitem()**: método remueve y devuelve **algún** par (key, value) del diccionario como una 2-tupla
- **d.values()**: devuelve una lista de los valores del diccionario
- **len(d)**: Retorna la longitud del diccionario (numero de keys)
- **del d['key']**: es la misma sentencia integrada del en el interprete Python pero aplicada al uso de la secuencia de tipo diccionario


<p><a name="stringsexercises"></a></p>

###2.4.4.1 Ejercicios de práctica

**Ejercicio 1: Dificultad Rookie**

Combine las siguientes dos listas en un diccionario

- keys = ['diez', 'veinte', 'treinta']
- values = [10, 20, 30]

resultado={"diez":10,"veinte":20,"treinta":30}

In [74]:
#Realice aqui el ejercicio
keys = ['diez', 'veinte', 'treinta']
values = [10, 20, 30]
dicc = dict(zip(keys,values))
dicc

{'diez': 10, 'treinta': 30, 'veinte': 20}

De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

keys = ['diez', 'veinte', 'treinta']
values = [10, 20, 30]

resultado=dict(zip(keys, values))
print(resultado)


--->

**Ejercicio 2: Dificultad Hero**

Combine los siguientes dos diccionarios en uno solo

- dict1 = {'Diez': 10, 'Veinte': 20, 'Treinta': 30}
- dict2 = {'Treinta': 30, 'Cuarenta': 40, 'Cincuenta': 50}

resultado={'Diez': 10, 'Veinte': 20, 'Treinta': 30,'Cuarenta': 40, 'Cincuenta': 50}

In [92]:
#Desarrolle aqui el ejercicio
dict1 = {'Diez': 10, 'Veinte': 20, 'Treinta': 30}
dict2 = {'Treinta': 30, 'Cuarenta': 40, 'Cincuenta': 50}
dict1_2 = dict1.copy()
dict1_2.update(dict2)
print(dict1_2)

{'Diez': 10, 'Veinte': 20, 'Treinta': 30, 'Cuarenta': 40, 'Cincuenta': 50}


De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

dict1 = {'Diez': 10, 'Veinte': 20, 'Treinta': 30}
dict2 = {'Treinta': 30, 'Cuarenta': 40, 'Cincuenta': 50}

resultado = dict1.copy()
resultado.update(dict2)
print(resultado)

--->


**Ejercicio 3: Dificultad Leyenda**

Extraiga la materia del icfes con el mayor puntaje

icfes = {
  'Fisica': 82,
  'Matematicas': 65,
  'Filosofia': 75,
  'Quimica':44,
  'Español':98
}


In [102]:
#Desarrolle aqui el ejercicio
icfes = {
  'Fisica': 82,
  'Matematicas': 65,
  'Filosofia': 75,
  'Quimica':44,
  'Español':98
}

r = max(icfes, key=icfes.get)
print(icfes[r])

98


98

De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

Oops los ejercicios de dificultad leyenda no tienen codigo, solo la solución correcta

Quimica

--->

<p><a name="controlFlow"></a></p>

## 2.5. Condicionales: if, elif, else

[[Secciones]](#sections)

La sintaxis en Python para la ejecución de una condición  consiste en las palabras claves `if`, `elif` (else if), `else`:

In [ ]:
statement1 = False
statement2 = False

if statement1:
    print("statement1 es Verdadero")

elif statement2:
    print("statement2 es Verdadero")

else:
    print("statement1 y statement2 son Falsos")

statement1 y statement2 son Falsos


También podemos tener sentencias if anidadas

In [ ]:
val = 100
if val < 200:
  print("El valor es menor a 200")
  if val == 150:
    print("es 150")
  elif val == 100:
    print("es 100")
  elif val == 50:
    print("es 50")
  elif val < 50:
    print("el valor es menor a 50")
else:
  print("El valor es mayor a 200")

El valor es menor a 200
es 100


In [ ]:
# Ve a la tienda y compra una caja de huevos, si hay leche trae 2 cajas
hay_leche=True
leches_compradas=0
huevos_comprados=0
if hay_leche:
  leches_compradas+=0
  huevos_comprados+=2
else:
  huevos_compradas+=0
#print("Traje ", leches_compradas, " de leche")   
#print("Traje ", huevos_comprados, " cajas de huevos")   

<p><a name="iter"></a></p>

## 2.6. Iteraciones y ciclos lógicos

En general, las instrucciones se ejecutan secuencialmente, pero puede haber casos  en los que se  necesite ejecutar un bloque de código varias veces.  Una instrucción de bucle nos permite ejecutar una instrucción o un grupo de instrucciones varias veces.

<p><a name="cicl"></a></p>

### 2.7.1. Ciclos for y while

El ciclo **for** ejecuta una secuencia de sentencias un número determinado de veces. La forma general de una sentencia para el **for** es la siguiente:



In [ ]:
"""
for variable in sequence:
     code block
"""     

'\nfor variable in sequence:\n     code block\n'

In [ ]:
range(10)

range(0, 10)

In [ ]:
suma=0
for i in range(10):
  suma+=i
  print('i=',i,'suma=',suma)

i= 0 suma= 0
i= 1 suma= 1
i= 2 suma= 3
i= 3 suma= 6
i= 4 suma= 10
i= 5 suma= 15
i= 6 suma= 21
i= 7 suma= 28
i= 8 suma= 36
i= 9 suma= 45


También podemos iterar sobre listas

In [ ]:
vocales=["a","e","i", "o","u"]
for i in vocales:
  print(i)

a
e
i
o
u


El ciclo **while** repite una sentencia o grupo de sentencias mientras una condición dada es **TRUE**. Antes de ejecutar el cuerpo del ciclo, python evalua la  condición 

**Ojo con los bucles infinitos!!**

In [ ]:
c = 10
while c > 0:
  print('c=',c,'se cumple la condición')
  c-=1

c= 4 se cumple la condición
c= 3 se cumple la condición
c= 2 se cumple la condición
c= 1 se cumple la condición


Podemos tener varias condiciones

In [ ]:
c = 10
while c > 0:
  if c > 1 and c!=5:
    print ("Voy a hacerlo "+str(c-1)+" veces más")
  elif c==5:
    print('Voy en '+str(c-1))
  else:
    print ("¡Este es el último!")
  c -= 1 #c=c-1

Voy a hacerlo 9 veces más
Voy a hacerlo 8 veces más
Voy a hacerlo 7 veces más
Voy a hacerlo 6 veces más
Voy a hacerlo 5 veces más
Voy en 4
Voy a hacerlo 3 veces más
Voy a hacerlo 2 veces más
Voy a hacerlo 1 veces más
¡Este es el último!


Podemos usar uno o más ciclos dentro de otro. Esto lo conocemos como ciclos anidados


In [ ]:
for i in range(2):
  for j in range(5):
    print("i: %d j: %d" %(i,j))

i: 0 j: 0
i: 0 j: 1
i: 0 j: 2
i: 0 j: 3
i: 0 j: 4
i: 1 j: 0
i: 1 j: 1
i: 1 j: 2
i: 1 j: 3
i: 1 j: 4


<p><a name="contr"></a></p>

### 2.7.2. Sentencias break y continue (control de ciclo)


Las sentencias de control de ciclo cambian la ejecución de su secuencia normal. Cuando la ejecución deja un ámbito, todos los objetos automáticos que se crearon en ese ámbito se destruyen.

La sentencia de control **break*** termina el ciclo actual y reanuda la ejecución en la siguiente instrucción.



In [ ]:
for i in vocales:
  if i=="o":
    break
  print(i)

a
e
i


La sentencia de control *continue* rechaza todas las declaraciones restantes en la iteración actual del ciclo y mueve el control de nuevo a la parte superior de este




In [ ]:
for i in vocales:
  if i=="o":
    continue
  print(i)

a
e
i
u


<p><a name="func"></a></p>

## 2.8. Funciones y clases

<p><a name="funci"></a></p>

### 2.8.1. Funciones

Una función es un bloque de código organizado y reutilizable que se utiliza para realizar una única acción relacionada. Las funciones proporcionan una mejor modularidad para su aplicación y un alto grado de reutilización de código. De momento hemos utilizado funciones preconstruidas en python, llegó la hora de diseñar nuestras propias funciones (user defined functions)

>`def NombreFuncion(arg1,arg2,...):`
>> `Cuerpo de la funcion (sentencias)`

Definamos la función exponencial $a^b$

In [ ]:
def Exp(a,b):
  exp = a**b
  print(exp)
  return
  
Exp(2,2)  

4


La sentencia *return* termina la función,  devolviendo opcionalmente uno o varios valores. Una declaración de retorno sin argumentos es lo mismo que devolver *none* (como en el caso anterior)

In [ ]:
def Exp(a,b):
  return a**b
  
def Exp2(a,b):
  return a**b,a**b+1,a**b+2

print(Exp(2,2),type(Exp(2,2)))

print(Exp2(2,2),type(Exp2(2,2)))


4 <class 'int'>
(4, 5, 6) <class 'tuple'>


#### Ejemplo 1
Escriba una funcion que retorne el valor maximo entre 2 números

In [ ]:
def maximo(x,y):
  if x >y:
    return x
  else:
    return y 

print(max(100,99.99999999))

100


#### Ejemplo 2
Escriba una funcion que reciba el nombre y apellido de una persona y que permita imprimirlo con el nombre primero o viceversa

In [ ]:
def printNombre(Nombre, Apellido,reverse=True):
  if reverse:
    print(Apellido + " ,"+Nombre)
  else:
    print(Nombre+ " ,"+ Apellido)  
printNombre("Florentino","Ariza")    

Ariza ,Florentino


En este ultimo ejemplo el argumento **reverse** se denomina keyword argument ya que es un parametro con valores predeterminados.

#### Ejemplo 3
Miremos el proximo ejemplo

In [ ]:
def f(x):
  y=1
  x=x+y 
  print("x= " ,x)
  return x

x=3
y=2
z=f(x)
print("z= ",z)
print("x= ",x)
print("y= ",y)

x=  4
z=  4
x=  3
y=  2


¿Por que hay dos valores diferentes de x?

La explicacion se debe al "alcance" (scope) de la funcion. Cada funcion crea en su interior un **espacio** definitorio de variables, tambien llamado **scope** .
El argumento formal **x** y la variable local **y** existen solo dentro de la funcion f(). 

#### Recursividad

Esta técnica tiene semejanza a las demostraciones por induccion en donde se requiere primero de un caso base que a veces especifica directamente los casos especiales, ademas se necesita un segundo componente que seria el caso **recursivo** (inductivo)

Veamos como utilizar la recursividad para programar la funcion n! (factorial). Recordemos:

- 3!=1 x 2 x 3
- 0!=1
- 4!=1 x 2 x 3 x 4

In [ ]:
def factorial(n):
  """
  Asumamos que n es un entero mayor a 0
  """
  if n==1 or n==0: #Caso base
    return 1
  else:
    return n*factorial(n-1)  #Caso inductivo
factorial(3)

6

**OJO** Aplicar recursiones es diferente a iterar con ciclos

<p><a name="functionexercises"></a></p>

###2.8.1.1 Ejercicios de práctica

**Ejercicio 1: Dificultad Zero**

Escriba una función que retorne el mayor de tres números

In [ ]:
#Desarrolle aqui el ejercicio

De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

def max_dos( x, y ):
    if x > y:
        return x
    return y
def max_tres( x, y, z ):
    return max_dos( x, max_dos( y, z ) )


--->

**Ejercicio 2: Dificultad Rookie**

Escriba una función que sume los valores de una lista que contiene numeros

In [ ]:
#Desarrolle aqui el ejercicio

De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

def suma(numeros):
    total = 0
    for x in numeros:
        total += x
    return total
    
--->


**Ejercicio 3: Dificultad Rookie**

Escriba una función que diga si un numero es par o impar

In [ ]:
#Desarrolle aqui el ejercicio


De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

def par_impar(x):
  if x%2==0:
    return(print("par"))
  else:
    return(print("impar"))
par_impar(17)
    
--->

**Ejercicio 4: Dificultad Rookie**

Escriba una función que reciba una lista con numeros y retorne una nueva lista sin valores repetidos

In [ ]:
#Desarrolle aqui el ejercicio

De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

def lista_sin_repetir(l):
  x = []
  for a in l:
    if a not in x:
      x.append(a)
  return x
    
--->

**Ejercicio 4: Dificultad Hero**

Escriba una función que diga si un numero es primo

In [ ]:
#Desarrolle aqui el ejercicio


**Ejercicio 5: Dificultad Leyenda**

Genere un numero aleatorio entre 1 y 9 (incluyendo al 1 y al 9). Pregunte al usuario por un numero, luego dgale si esta por debajo, o por encima, o finalmente correcto. (Pista: utilice la funcion **input** y el modulo **random** para este ejercicio)

Extras:

- El juego sigue actvo hasta que el jugador escriba “exit” o adivine el numero
- Lleve registro del numero de intentos que le toma al jugador, imprima este valor cuando el juego termine.

De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

def es_primo(n):
    if (n==1):
        return False
    elif (n==2):
        return True;
    else:
        for x in range(2,int(n**0.5)):
            if(n % x==0):
                return False
        return True    

    
--->


<p><a name="class"></a></p>

### 2.8.2 Programacion Orientada a Objetos (Clases)
El paradigma de la programacion orientada a objetos se basa en la modelacion de datos y operaciones como uan pareja intimamente relacionada en lugar de elementos separados.

Como primer ejemplo imagine una fotografia digital, la cual puede ser considerada por algunos como una simple coleccionde informacion (pixeles). Sin embargo, en un framework de programacion orientada a objetos la imagen es en realidad un objeto que puede soporta multiples operaciones en sí tales como rotacion, cambio de escala, filtros, etc.. 



Las clases proporcionan un medio de agrupar datos y "funcionalidad". La creación de una nueva clase crea un nuevo tipo de objeto, lo que permite crear nuevas *instancias* de ese tipo. Cada instancia de la clase puede tener sus propios atributos. Las instancias de una clase también pueden tener *métodos* (definidos por su clase) para modificar su estado.

>class Name():
>>sentencias

Los atributos son como propiedades que queremos añadir a la clase 

In [ ]:
#Creamos la clase television con la configuracion de fabrica
class Television:
  def __init__(self):
    self._powerOn = False
    self._muted = False
    self._volume = 5
    self._channel = 2
    self._prevChan = 2


Dentro de las clases podemos definir funciones, conocidas como *métodos* 

In [ ]:
#Creamos la clase television con la configuracion de fabrica
class Television:
  def __init__(self):
    self._powerOn = False
    self._muted = False
    self._volume = 5
    self._channel = 2
    self._prevChan = 2
  #Metodo de encendido y apagado
  def togglePower(self):
    self._powerOn = not self._powerOn
  #Metodo de Mute
  def toggleMute(self):
    if self._powerOn:
      self._muted = not self._muted

  # Metodo para subir volumen
  def volumeUp(self):
    if self._powerOn:
      if self._volume < 10:
        self._volume += 1
        self._muted = False
        return self._volume
  #Metodo para cambiar de canal
  def channelUp(self):
    if self._powerOn:
      self._prevChan = self._channel # record the current value
      if self._channel == 99:
        self._channel = 2 # wrap around to minimum
      else:
        self._channel += 1
      return self._channel
  #Previous channel

  def jumpPrevChannel(self):
    if self._powerOn:
      incoming = self._channel
      self._channel = self._prevChan
      self._prevChan = incoming
      return self._channel

  def __str__(self):
    display = 'Power setting is currently ' + str(self._powerOn) +'\n'
    display += 'Volume setting is currently ' + str(self._volume) +'\n'
    display += 'Mute is currently ' + str(self._muted)
    return display



Los métodos necesitan tener un argumento convenientemente llamado self, que se refiere al objeto del método que está siendo llamado. Podemos pasar más de un argumento si así lo deseamos

Utilicemos el televisor luego de sacarlo de la caja

In [ ]:
televisor_sala=Television()

In [ ]:
#Encendamos el televisor
televisor_sala.togglePower()
print(televisor_sala)

Power setting is currently True
Volume setting is currently 5
Mute is currently False


In [ ]:
#Subamos el volumen a 8
televisor_sala.volumeUp()
televisor_sala.volumeUp()
televisor_sala.volumeUp()
print(televisor_sala)

Power setting is currently True
Volume setting is currently 8
Mute is currently False


In [ ]:
#Pongamos el tour para ver a Nairo y a Egan
televisor_sala.channelUp()
print(televisor_sala)
print("Canal" , televisor_sala._channel)

Power setting is currently True
Volume setting is currently 8
Mute is currently False
Canal 7


#### Aplicacion financiera de OOP: HIPOTECAS (Caso Avanzado)

In [ ]:
#Tomado de Guttag, J. V. (2013). Introduction to computation and programming using Python. Mit Press.
import pylab
def findPayment(loan, r, m):
    """Assumes: loan and r are floats, m an int
    Returns the monthly payment for a mortgage of size
    loan at a monthly rate of r for m months"""
    return loan*((r*(1+r)**m)/((1+r)**m - 1))

class Mortgage(object):
    """Abstract class for building different kinds of mortgages"""
    def __init__(self, loan, annRate, months):
        """Create a new mortgage"""
        self.loan = loan
        self.rate = annRate/12.0
        self.months = months
        self.paid = [0.0]
        self.owed = [loan]
        self.payment = findPayment(loan, self.rate, months)
        self.legend = None #description of mortgage

    def makePayment(self):
        """Make a payment"""
        self.paid.append(self.payment)
        reduction = self.payment - self.owed[-1]*self.rate
        self.owed.append(self.owed[-1] - reduction)

    def getTotalPaid(self):
        """Return the total amount paid so far"""
        return sum(self.paid)

    def __str__(self):
        return self.legend


# fixed-rate mortgage
class Fixed(Mortgage):
    def __init__(self, loan, r, months):
        Mortgage.__init__(self, loan, r, months)
        self.legend = 'Fixed, ' + str(r*100) + '%'

# fixed-rate mortgage with up-front points
class FixedWithPts(Fixed):
    def __init__(self, loan, r, months, pts):
        Fixed.__init__(self, loan, r, months)
        self.pts = pts
        self.paid = [loan*(pts/100.0)]
        self.legend += ', ' + str(pts) + ' points'

# mortgage that changes interest rate after 48 months
class TwoRate(Mortgage):
    def __init__(self,loan,r,months,teaserRate,teaserMonths):
        Mortgage.__init__(self, loan, teaserRate, months)
        self.teaserMonths = teaserMonths
        self.teaserRate = teaserRate
        self.nextRate = r/12.0
        self.legend = str(teaserRate*100)\
            + '% for ' + str(self.teaserMonths)\
            + ' months, then ' + str(r*100) + '%'

    def makePayment(self):
        if len(self.paid) == self.teaserMonths + 1:
            self.rate = self.nextRate
            self.payment = findPayment(self.owed[-1], self.rate,
                                       self.months - \
                                       self.teaserMonths)
        Mortgage.makePayment(self)


# helper function to try out alternatives
def compareMortgages(amt, years, fixedRate, pts, ptsRate,
                     varRate1, varRate2, varMonths):
    # create alternative mortgages
    totMonths = years*12
    fixed1 = Fixed(amt, fixedRate, totMonths)
    fixed2 = FixedWithPts(amt, ptsRate, totMonths, pts)
    twoRate = TwoRate(amt, varRate2, totMonths, varRate1,
                      varMonths)
    morts = [fixed1, fixed2, twoRate]
    
    # run experiment!
    for m in range(totMonths):
        for mort in morts:
            mort.makePayment()
            
    # report results
    for m in morts:
        print (m)
        print (' Total payments = $' + str(int(m.getTotalPaid())))

# amount borrowed: $200,000
# term: 30 years
#  option 1: rate = 7%
#  option 2: 3.25 points upfront, rate = 5%
#  option 3: 48 months of rate = 5%, then rate = 9.5%

compareMortgages(amt=200000, years=30,
                 fixedRate=0.07,
                 pts = 3.25, ptsRate=0.05,
                 varRate1=0.045, varRate2=0.095, varMonths=48)
  


Fixed, 7.000000000000001%
 Total payments = $479017
Fixed, 5.0%, 3.25 points
 Total payments = $393011
4.5% for 48 months, then 9.5%
 Total payments = $551444


<p><a name="inout"></a></p>

## 2.9. Archivos de entrada y salida

<p><a name="lecte"></a></p>

### 2.9.1. Lectura de entrada de teclado

Python proporciona una función integrada <code>input()</code> para leer una línea de texto de la entrada estándar

In [ ]:
a = input('Ingresa un número ')
print('El número que ingresaste es:',a)
type(a)


Ingresa un número 4
El número que ingresaste es: 4


str


independientemente de lo que ingrese como entrada, la función <code>input()</code> siempre lo convierte en una cadena de caracteres. Podemos utilizar las funciones <code>int()</code> y <code>float()</code> para obtener enteros y números de punto flotante respectivamente

In [ ]:
numero_entero = int(input('Ingresa un número'))
print(numero_entero,type(numero_entero))

numero_pflotante = float(input('Ingresa un número'))
print(numero_pflotante,type(numero_pflotante))

Ingresa in unúmero4
4 <class 'int'>
Ingresa un número1.2
1.2 <class 'float'>


<p><a name="apyci"></a></p>

### 2.9.2. Apertura y cierre de archivos

Python proporciona funciones básicas y métodos necesarios para manipular archivos de forma predeterminada. Se puede realizar la mayor parte de la manipulación de archivos utilizando un objeto tipo <code>file</code>. Antes de poder leer o escribir un archivo, debemos abrirlo con la función <code> open() </code>incorporada de Python. Para cerrarlo utilizamos la función <code>close()</code>.

In [ ]:
fo = open("foo.txt", "w")
print("Nombre del archivo: ", fo.name)
print('Modo con el que se abrió el archivo:',fo.mode)
print('Cerrado:',fo.closed)
fo.close()
print('Cerrado:',fo.closed)

Nombre del archivo:  foo.txt
Modo con el que se abrió el archivo: w
Cerrado: False
Cerrado: True


Modos comunes: w (Escritura), r (Lectura), a (Añadir)

<p><a name="leyes"></a></p>

### 2.9.3. Leer y escribir archivos

El objeto <code>file</code> proporciona un conjunto de métodos de acceso para facilitar nuestras vidas. Veríamos cómo usar los métodos <code>write()</code> y <code>read()</code> para leer y escribir archivos.

In [ ]:
fo = open("foo.txt", "w")
fo.write( "¡Hola \n mundo!")
fo.close()

!cat foo.txt

¡Hola 
 mundo!

In [ ]:
fo = open("foo.txt", "r")

print(fo.readline())

#print(fo.read())

#print(fo.read(2))

fo.close()

¡Hola 



<p><a name="subar"></a></p>

### 2.9.4. Subir archivos locales

El método <code>files.upload</code> devolverá un diccionario de los archivos que se han subido. Al diccionario se le asignará el nombre del archivo como clave y los valores serán los datos que se han subido (los archivos permanecen en la máquina virtual por 12 horas)

In [ ]:
from google.colab import files

uploaded = files.upload()

<p><a name="des"></a></p>

### 2.9.5. Descargar archivos en tu sistema local 

El método <code>files.download</code> invocará al navegador para que descargue el archivo en tu ordenador local.

In [ ]:
from google.colab import files

with open('example.txt', 'w') as f:
  f.write('some content')

files.download('example.txt')

<p><a name="goodr"></a></p>

### 2.9.6. Google drive: Paquete PyDrive

Instalamos el paquete

In [ ]:
!pip install --upgrade --quiet PyDrive

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

     |████████████████████████████████| 993kB 46.0MB/s 


Nos autenticamos

In [ ]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

Subir un archivo al Drive

In [ ]:
uploaded = drive.CreateFile({'title': 'Sample upload.txt'})
uploaded.SetContentString('Sample upload file content')
uploaded.Upload()
print('Uploaded file with ID {}'.format(uploaded.get('id')))

Uploaded file with ID 1chgUFynYuS1sD4AsNbrU9R3JXTYE2nLM


Descargar un archivo del Drive

In [ ]:
i='1kKIxeYVO6Ixe4TNxrmwDgSvVrBMHel37'
downloaded = drive.CreateFile({'id': i})
downloaded.GetContentFile('Sample upload.txt') 
print('Downloaded content "{}"'.format(downloaded.GetContentString()))

Downloaded content "Sample upload file content"


In [ ]:
#la "id" es lo que va después del = : https://drive.google.com/open?id=1kKIxeYVO6Ixe4TNxrmwDgSvVrBMHel37

<p><a name="git"></a></p>

### 2.9.7 Github

In [ ]:
!git clone https://github.com/username/repositorio

Cloning into 'repositorio'...
fatal: could not read Username for 'https://github.com': No such device or address


<p><a name="numpy"></a></p>

## 3.0 Numpy

[[Secciones]](#sections)

El paquete (modulo) numpy es usado en practicamnte toda operacion numerica en python. Es un paquete que provee vectores, matrices y estrucutras de datos de altas dimensiones con buen desempeño. Esta implementado en C y fortran haciendo por tanto uso de una vectorizacion eficiente.


In [ ]:
# Numpy suele importarse con la siguiente convencion (en todo el mundo!)
import numpy as np

<p><a name="numpyarrays"></a></p>

### 3.1 Arrays

El elemento basico de numpy son los arrays (arreglos). Un array  es un grid de valores, del mismo tipo, los cuales son indexados por una tupla de enteros no negativos. El número de dimensiones es el **rango** de la matriz; la **forma** (shape) de la matríz es una tupla de enteros dados por el tamaño del array a lo largo de cada dimensión.

Podemos inicializar los arrays de numpy mediante listas de Python y acceder a los elementos mediante corchetes []

<p><img alt="comparison  logo" width="400" height="200" src="https://miro.medium.com/max/3184/1*X0Dg7QfSYtWhSAu-afi8-g.png" align="center" hspace="10px" vspace="0px"></p>

In [ ]:
# Como se crean los arrays

a = np.array([1,2,3]) # Creación de un array de rango 1
b = np.array([(1.5,2,3), (4,5,6)], dtype = float) # Creación de un array de rango 2
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)
print("array b")
print(b)
print(type(b)) #
print(b.shape) # Veamos la forma

array b
[[1.5 2.  3. ]
 [4.  5.  6. ]]
<class 'numpy.ndarray'>
(2, 3)


In [ ]:
c = np.array([[0,1,2,3],[4,5,6,7]])    # Creación de un array de rango 2
print(c.shape)                     # Forma "(2, 4)"
print(b[0, 0], b[0, 1], b[1, 0])   # Indexacion con enteros, impresión de los elementos 0, 1 y 4


(2, 4)
1.5 2.0 4.0


In [ ]:
# Atajos
a=np.zeros((2,2)) # Imprime "[[ 0.  0.]
                #            [ 0.  0.]]"
print("Array con ceros",a)
print("------------")

b=np.ones((2,3,4),dtype=np.int16)  #Crea un array de unos
print("Array de unos", b)
print("------------")

c = np.arange(0, 32, 2)                    # Creación de un vector lleno de una secuencia lineal
print("Array de una secuencia lineal" ,c)  # que comience en 0, finalice en 30, con paso 2.
print("------------")

d = np.linspace(0, 1, 10)                   # Crea un vector de 10 valores espaciados 
print("Array de una secuencia lineal",d)    # uniformemente entre 0 y 1.   
print("------------")

e = np.full((2,2),7) # Crea un array de valores constantes
print("Array de valores constantes",e)
print("------------")

f = np.eye(2) #Crea l matriz identidad de dimension  2X2 
print("Matriz identidad 2x2", f)
print("------------")

g = np.random.random((2,2))                # Creación de una matriz de 2x2 de valores aleatorios.
print("Array de números aleatorios(u)", g) # distribuidos uniformemente.
print("------------")

h = np.random.normal(0, 1, (3, 3))         # Creación una matriz 3x3 de valores aleatorios normalmente 
print("Array de números aleatorios(n)", h) # distribuidos con media 0 y desviación estándar 1.
print("------------")

i = np.random.randint(0, 10, (3, 3))       # Creación de una matriz 3x3 de números enteros aleatorios
print("Array de números aleatorios(i)",i)  # en el intervalo [0,10)
print("------------")

j=np.empty((3,2))  #Crea un array vacio
print("Array vacio", j)

Array con ceros [[0. 0.]
 [0. 0.]]
------------
Array de unos [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
------------
Array de una secuencia lineal [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
------------
Array de una secuencia lineal [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
------------
Array de valores constantes [[7 7]
 [7 7]]
------------
Matriz identidad 2x2 [[1. 0.]
 [0. 1.]]
------------
Array de números aleatorios(u) [[0.37994923 0.43258771]
 [0.61953416 0.8718526 ]]
------------
Array de números aleatorios(n) [[-1.60133181 -0.26946609  1.44999125]
 [ 1.10492876  1.0029791   0.73151984]
 [-0.80960126 -0.06894503  0.56802468]]
------------
Array de números aleatorios(i) [[9 7 8]
 [0 3 7]
 [3 1 7]]
------------
Array vacio [[1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]]


<p><a name="arraysATT"></a></p>

###3.2. Atributos

Cada array tiene como atributos: <code>ndim</code>  (el número de dimensiones), <code>shape</code> (el tamaño de cada dimensión) y <code>size</code> (el tamaño total de la matriz o número de elementos):


In [ ]:
v1 = np.random.randint(20, size=6)          # array unidimensional
v2 = np.random.randint(20, size=(3, 4))     # array bidimensional
v3 = np.random.randint(20, size=(3, 4, 5))  # array tridimensional

print("x1 ndim: ", v1.ndim)
print("x1 shape:", v1.shape)
print("x1 size: ", v1.size,"\n")

print("x2 ndim: ", v2.ndim)
print("x2 shape:", v2.shape)
print("x2 size: ", v2.size, "\n")

print("x3 ndim: ", v3.ndim)
print("x3 shape:", v3.shape)
print("x3 size: ", v3.size)

x1 ndim:  1
x1 shape: (6,)
x1 size:  6 

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12 

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Otros atributos incluyen <code>itemsize</code>, que enumera el tamaño (en bytes) de cada elemento del array,
y <code>nbytes</code>, que enumera el tamaño total (en bytes) del array

In [ ]:
print("itemsize:", v3.itemsize, "bytes")
print("nbytes:", v3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


<p><a name="arraysIDX"></a></p>

### 3.3 Indexación

[[Contenidos]](#contents)

Al igual que en las librerias estándar de Python, se puede acceder an n-ésimo componente de un array especificando el índice deseado entre [] corchotes

In [ ]:
print(v1)

print(v1[0])

[17 15  8  1  2  3]
17


En el caso de un array multidimensional, se accede a los elementos utilizando los índices separados por comas

In [ ]:
print(v2)

print(v2[0,1])

[[14  9  2 13]
 [11  6  4 12]
 [13 11  4 13]]
9


Recordemos que los arrays en NumPy tiene un tipo fijo. Si intentamos insertar un número de tipo flotante en un array de tipo entero, el valor se truncará

In [ ]:
print("v1 original") #Nuestro v1 contenia valores enteros
print(v1)
v1[0] = 3.1415
print("v1 editado") #Al ingresar un float igual se conserva el tipo int
print(v1)

v1 original
[17 15  8  1  2  3]
v1 editado
[ 3 15  8  1  2  3]


En el caso tridimensional

In [ ]:
print(v3,"\n")

print("Dos formas de acceder al mismo elemento: \n")
print("v3[1][1][0] =", v3[1][1][0])
print("v3[1,1,0] =", v3[1,1,0])

[[[ 4  9  1  4 10]
  [ 3 12  9  3 10]
  [14  9  8  5 11]
  [19  0 10  5  6]]

 [[ 9  9  6  2 13]
  [12 10  1  5  9]
  [13  2  9 19  3]
  [11 11  7  5 16]]

 [[14  2 17 14 17]
  [ 0 16  7  8  0]
  [ 2 15 17  1  5]
  [ 0 12  4  1  9]]] 

Dos formas de acceder al mismo elemento: 

v3[1][1][0] = 12
v3[1,1,0] = 12


#### Ejercicios de practica

Cree un array v4 de dimension 4 con numeros enteros entre 1 y 10 con forma (2,2). Luego, imprima los siguientes atributos
para verificar su resultado:
 - ndim
 - shape
 - size


In [ ]:
# Desarrolle aqui el ejercicio


De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

v4=np.random.randint(10,size=(4,2,2))
v4=np.random.randint(10,size=(4,2,2))
print(v4)
--->


<p><a name="arraysSLI"></a></p>

### 3.3 Segmentación

[[Secciones]](#sections)

La sintaxis de segmentación en NumPy e igual al de  las listas estándar en Python: <code>x[inicio:final:paso]</code>

In [ ]:
x = np.arange(10)     

print(x)

print('Primeros 5 elementos ',x[:5])

print('Elementos luego del índice 5 ',x[5:])

print('Subarray medio ',x[4:7])

print('Subarray medio2', x[4:-3])

print('Elementos separados por dos elementos ',x[::2])

print('Elementos separados por dos elementos comenzando en el index 1 ',x[1::2])

[0 1 2 3 4 5 6 7 8 9]
Primeros cinco elementos  [0 1 2 3 4]
Elementos luego del índice 5  [5 6 7 8 9]
Subarray medio  [4 5 6]
Subarray medio2 [4 5 6]
Elementos separados por dos elementos  [0 2 4 6 8]
Elementos separados por dos elementos comenzando en el index 1  [1 3 5 7 9]


Un caso  confuso es cuando el valor del paso es negativo. En este caso, los valores predeterminados para <code>inicio</code> y 
<code>final</code> se intercambian.

In [ ]:
print(x[::-1])      # Se reversan todos los elementos 

print(x[5::-2])     # Se reversan los elementos desde el índice 5 con paso 2 

[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


Para los arrays multidimensionales la segmentación se hace de una manera similar, por ejemplo:

In [ ]:
print("Array v2")
print(v2)
print("---------")
print('Dos filas, tres columnas')
print(v2[:2, :3])  
print("-------------------------------")
print('Todas las filas, dos columnas')
print(v2[:, :2])      
print("-------------------------------")
print('Dos filas, el resto de columnas con paso 2')
print(v2[:2, ::2])        
print("-------------------------------")
print('Primera fila')
print(v2[0])

Array v2
[[14  9  2 13]
 [11  6  4 12]
 [13 11  4 13]]
---------
Dos filas, tres columnas
[[14  9  2]
 [11  6  4]]
-------------------------------
Todas las filas, dos columnas
[[14  9]
 [11  6]
 [13 11]]
-------------------------------
Dos filas, el resto de columnas con paso 2
[[14  2]
 [11  4]]
-------------------------------
Primera fila
[14  9  2 13]


In [ ]:
print(v3)
print("-------------------------------")
print('Tercer array, dos filas y tres columnas')
print(v3[2,:2,:3])
print("-------------------------------")
print('Hasta el 2do array, dos filas y dos columnas')
print(v3[:2,:2,:2])

[[[ 4  9  1  4 10]
  [ 3 12  9  3 10]
  [14  9  8  5 11]
  [19  0 10  5  6]]

 [[ 9  9  6  2 13]
  [12 10  1  5  9]
  [13  2  9 19  3]
  [11 11  7  5 16]]

 [[14  2 17 14 17]
  [ 0 16  7  8  0]
  [ 2 15 17  1  5]
  [ 0 12  4  1  9]]]
-------------------------------
Tercer array, dos filas y tres columnas
[[14  2 17]
 [ 0 16  7]]
-------------------------------
Hasta el 2do array, dos filas y dos columnas
[[[ 4  9]
  [ 3 12]]

 [[ 9  9]
  [12 10]]]


Es importante tener en cuenta que la segmentación de arrays en NumPy devuelve **vistas**  en lugar de **copias** de los datos del array. Esto significa que cuando trabajamos con grandes conjuntos de datos, podemos acceder y procesar partes de estos conjuntos de datos sin la necesidad de copiar el búfer de datos subyacente.

In [ ]:
print('Array original \n',v2)

sub_array = v2[:2,:2]

sub_array[0,0] = 999

print('Array luego de modificar el subarray \n',v2)

Array original 
 [[14  9  2 13]
 [11  6  4 12]
 [13 11  4 13]]
Array luego de modificar el subarray 
 [[999   9   2  13]
 [ 11   6   4  12]
 [ 13  11   4  13]]


A veces es útil copiar explícitamente los datos dentro de un array o un  subarray. Esto se puede hacer con el
método <code>copy()</code>

In [ ]:
sub_array_copia = v2[:2,:2].copy()
sub_array_copia[0,0] = 20

print(sub_array_copia)
print(5*'-')
print(v2)

[[20  9]
 [11  6]]
-----
[[999   9   2  13]
 [ 11   6   4  12]
 [ 13  11   4  13]]


<p><a name="arraysRES"></a></p>

### 3.4 Reshape

[[Secciones]](#sections)

Otro tipo útil de operación es el "reshape" o cambio de forma de un array, una operación semejante pero no limitada a la transposición de matrices. La forma más flexible de hacerlo es con el método <code>reshape()</code>. 



In [ ]:
grid = np.arange(1, 10).reshape((3, 3))            
print(grid)

a = np.array([[1,2,3], [4,5,6]]).reshape(1,6)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6]]


Podemos convertir un array unidimensional en un vector fila o columna bidimensional 



In [ ]:
x = np.array([1,2,3])

fil_x = x.reshape((1,3))    # vector fila
col_x = x.reshape((3,1))    # vector columna

print("Vector Fila")
print(fil_x)
print("---------")
print("Vector Columna")
print(col_x)

Vector Fila
[[1 2 3]]
---------
Vector Columna
[[1]
 [2]
 [3]]


<p><a name="arraysCON"></a></p>

### 3.5. Concatenación y división de arrays

[[Secciones]](#sections)

Numpy nos permite combinar varios arrays en uno solo o, por el contrario, dividir un array en varios. La concatenación, o unión de dos arrays en NumPy, se realiza principalmente a través de la función <code>np.concatenate</code>


In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.concatenate([x, y])
print(z)

[1 2 3 3 2 1]



También se puede utilizar para arrays bidimensionales

In [ ]:
grid = np.array([[1, 2, 3], [4, 5, 6]])

z1 = np.concatenate([grid,grid])            # concatenar a lo largo del primer eje
print(z1)
print('-------------------------')
z2 = np.concatenate([grid,grid], axis=1)    # concatenar a lo largo del segundo eje
print(z2)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
-------------------------
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


Para trabajar con arrays de dimensiones mixtas es recomendable usar las funciones  <code>np.vstack</code> y <code>np.hstack</code>. 


In [ ]:
# Apilar verticalmente los arrays
x = np.array([11, 44, 55])
z1 = np.vstack([x,grid])
print(z1)

print('------------------------------')
# Apilar horizontalmente los arrays
y = np.array([[99], [99]])
z2 = np.hstack([grid, y])
print(z2)

[[11 44 55]
 [ 1  2  3]
 [ 4  5  6]]
------------------------------
[[ 1  2  3 99]
 [ 4  5  6 99]]


Lo opuesto a la concatenación es la división, que se implementa mediante las funciones <code>np.split</code>, <code>np.hsplit</code> y <code>np.vsplit</code>


In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Note que las funciones `np.hsplit` y `np.vsplit` son similares

In [ ]:
grilla = np.arange(16).reshape((4, 4))

sup, inf = np.vsplit(grilla, [2])
print(sup)
print(5*'-')
print(inf)

[[0 1 2 3]
 [4 5 6 7]]
-----
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
izq, der = np.hsplit(grilla, [2])
print(izq)
print(5*'-')
print(der)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
-----
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


<p><a name="arrayMath"></a></p>


### 3.6. Operaciones vectorizadas
[[Secciones]](#sections)

El cálculo con arrays en NumPy puede ser muy rápido o muy lento. La clave para hacerlo rápido es usar operaciones **vectorizadas**, generalmente implementadas a través de las funciones **universales** de NumPy (ufuncs)

In [ ]:
#Estrategia Iterativa (No hago uso de vectorizacion)
def compute_reciprocals(values):
  #Creamos un array vacio para almacenar nuestros calculos
  output = np.empty(len(values))
  for i in range(len(values)):
    #Para cada valor calculamos su reciproco (inverso multiplicativo)
    output[i] = 1.0 / values[i]
  return output


big_array = np.random.randint(1, 100, size=1000000) 

print("Tiempo de la estrategia iterativa")
%timeit compute_reciprocals(big_array)          # calculo en ciclo
print("Tiempo de la estrategia usando vectorización")
%timeit (1.0 / big_array)                       # calculo vectorizado

Tiempo de la estrategia iterativa
1 loop, best of 3: 1.9 s per loop
Tiempo de la estrategia usando vectorización
100 loops, best of 3: 2.08 ms per loop


Las operaciones vectorizadas en NumPy se implementan a través de las **ufuncs** (funciones universales), cuyo objetivo  es ejecutar rápidamente operaciones de forma repetida sobre valores de arrays. Las operaciones con **ufuncs** aplican tnato para arrays unidimensionales como para arrays multidimensionales. 

In [ ]:
print(np.arange(5) / np.arange(1, 6))         # Operación sobre array unidimensional

print('-----------------------')
x = np.arange(9).reshape((3, 3))              # Operación sobre array multidimensional
print(2**x)

[0.         0.5        0.66666667 0.75       0.8       ]
-----------------------
[[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]


Los cálculos que usan vectorización a través de ufuncs son casi siempre **más eficientes** que su contraparte implementada a través de ciclos, especialmente a medida que los arrays crecen en tamaño. **Consejo:** Cada vez que se vea un ciclo de este tipo en un script de Python, debe considerarse la posibilidad de reemplazarlo con una expresión vectorizada.

### 3.7. Ufuncs
Se puede consultar mas sobre las funciones universales de numpy en el siguiente enlace:
https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [ ]:
x = np.arange(1,5)
print(x)

# Operadores aritméticos
print("Operadores Aritmeticos")
print('x+2 ',np.add(x,2))
print('x-2 ',np.subtract(x,2))
print('-x ',np.negative(x))
print('x*2 ',np.multiply(x,2))
print('x/2 ',np.divide(x,2))
print('x^2 ',np.power(x,2))
print("----------------------")
# Funciones trigonométricas
print("Funciones trigonométricas")
theta = np.linspace(0,np.pi,3)

print('sin(theta)',np.sin(theta))
print('cos(theta)',np.cos(theta))
print("----------------------")
print("Exponenciales y logaritmos")
# Exponenciales y logaritmos
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

[1 2 3 4]
Operadores Aritmeticos
x+2  [3 4 5 6]
x-2  [-1  0  1  2]
-x  [-1 -2 -3 -4]
x*2  [2 4 6 8]
x/2  [0.5 1.  1.5 2. ]
x^2  [ 1  4  9 16]
----------------------
Funciones trigonométricas
sin(theta) [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) [ 1.000000e+00  6.123234e-17 -1.000000e+00]
----------------------
Exponenciales y logaritmos
e^x = [ 2.71828183  7.3890561  20.08553692 54.59815003]
2^x = [ 2.  4.  8. 16.]
3^x = [ 3  9 27 81]
ln(x) = [0.         0.69314718 1.09861229 1.38629436]
log2(x) = [0.        1.        1.5849625 2.       ]
log10(x) = [0.         0.30103    0.47712125 0.60205999]


### 3.8. Operaciones Básicas.

Las operaciones matematicas basicas entre arrays, son operaciones **elemento a elemento** (elementwise):

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Suma elemento a elemento
print("Suma elemento a elemento")
print(x + y)
print(np.add(x, y))
print("----------------------")

# Resta elemento a elemento.
print("Resta elemento a elemento.")
print(x - y)
print(np.subtract(x, y))
print("----------------------")

# Multiplicación elemento a elemento.
print("Multiplicación elemento a elemento.")
print(x * y)
print(np.multiply(x, y))
print("----------------------")

# División elemento a elemento.
print("División elemento a elemento.")
print(x / y)
print(np.divide(x, y))
print("----------------------")

print("Raiz cuadrada a cada elmento.")
# Raiz cuadrada a cada elmento.
print(np.sqrt(x))

Suma elemento a elemento
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
----------------------
Resta elemento a elemento.
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
----------------------
Multiplicación elemento a elemento.
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
----------------------
División elemento a elemento.
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
----------------------
Raiz cuadrada a cada elmento.
[[1.         1.41421356]
 [1.73205081 2.        ]]


Nótese que la multiplicación mediante el operador `*` corresponde a una multiplicación elemento a elemento entre dos arrays. En Python, la multiplicación matricial entre dos arrays se realiza mediante la función punto (`dot`).

In [ ]:
import numpy as np

x = np.array([[8,2],[5,4]])
y = np.array([[10,32],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Producto entre vectores
print("Producto vector-vector",v.dot(w))
print("Producto vector-vector", np.dot(v, w),"\n")
print("----------------------")
# Producto matriz/vector;
print("Producto matriz/vector \n",x.dot(v))
print("Producto matriz/vector \n", np.dot(x, v),"\n")
print("----------------------")
# Producto matrix/matrix ; 
print("Producto matriz/matriz \n",x.dot(y),"\n")
print("Producto matriz/matriz \n",np.dot(x, y))

Producto vector-vector 219
Producto vector-vector 219 

----------------------
Producto matriz/vector 
 [92 85]
Producto matriz/vector 
 [92 85] 

----------------------
Producto matriz/matriz 
 [[ 94 272]
 [ 78 192]] 

Producto matriz/matriz 
 [[ 94 272]
 [ 78 192]]


Python proporciona algunas funciones para realizar operaciones sobre los arrays. 
Por ejemplo, la función `sum` realiza una suma sobre todos los elementos del array:

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])

print("Suma total de los elementos del array", np.sum(x))  # Calculo de la suma de todos los elementos.
print("Suma de cada columna",np.sum(x, axis=0))  # Suma de cada columna
print("Suma de cada fila",np.sum(x, axis=1))  # Suma de cada fila

Suma total de los elementos del array 10
Suma de cada columna [4 6]
Suma de cada fila [3 7]


Para muchas más funciones pueden consultar [este enlace](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

<p><a name="bcasting"></a></p>

### 3.9. Broadcasting.

[[Secciones]](#sections)

El Broadcasting es una potente herramienta que nos permite trabajar en numpy con arrays de diferentes tamaños para realizar operaciones aritméticas. A menudo tenemos un array mas pequeño y otro de tamaño mayor, de tal forma que queremos usar el array más pequeño varias veces para realizar algunas operaciones en el array mas grande.

<p><img alt="comparison  logo" width="400" height="200" src="https://1.bp.blogspot.com/-BwqTkW7_hxk/XuTCd6axFBI/AAAAAAAAEB4/Izf7AH2tEmsbIPY0h0UFPIsDltFgHp0_gCK4BGAsYHg/s799/broadcasting%2Bnumpy.png" align="center" hspace="10px" vspace="0px"></p>



Supongamos, por ejemplo, que se quiere adicionar un vector constante a cada fila de una matriz. Podemos realizar esto de la siguiente forma:

In [ ]:
import numpy as np

x = np.arange(start = 1, stop = 13, step = 1).reshape((4,3)); # Array de 4x3 
y = np.array([1,0,1]) # Vector fila
v = np.empty_like(x) #Array vacio de la mismas dimensiones que x

# Modificación del array x, sumando en cada fila el vector fila y.

for i in range(len(x)):
  v[i,:] = x[i,:]+y

print("Array Original")
print(x)
print("")
print("Array luego de adicionar valores")
print(v)

Array Original
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Array luego de adicionar valores
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


A continuación se muestra la solución al anterior problema usando broadcasting:

In [ ]:
x = np.arange(start = 1, stop = 13, step = 1).reshape((4,3)); # Array de 4x3 
y = np.array([1,0,1]) # Vector fila

v = x+y
print(v)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


<p><a name="tnumpy"></a></p>

### 3.99. Ejercicios de Práctica 

[[Secciones]](#sections)

**Ejercicio 1: Dificultad Zero**

Demuestre que la multiplicación de una matriz $A$ de $7\times7$ por la matriz identidad $I$ es igual a la matriz $A$

In [ ]:
#Desarrolle aqui su ejercicio

De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

identdad = np.eye(7,7)
A1 = np.random.rand(7,7)
A2 = A1.dot(identity)
if A2==A1:
    print('Correcto')
else:
    print('No es correcto')

print("La matriz A1 es ", A1)
print("La matriz A2 es ", A2)

--->

**Ejercicio 2: Dificultad Zero**

Escriba un programa de NumPy  que genere un array que contenga los enteros del 30 al 70

In [ ]:
#Desarrolle aqui su ejercicio

De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

import numpy as np
array=np.arange(30,71)
print("Array de los enteros de 30 a 70")
print(array)

--->

**Ejercicio 3: Dificultad Zero**

Escriba un programa de NumPy  que genere un array que contenga los enteros pares del 30 al 70

In [ ]:
#Desarrolle aqui su ejercicio

De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

import numpy as np
array=np.arange(30,71,2)
print("Array de los enteros pares del 30 al 70")
print(array) 

--->

**Ejercicio 3: Dificultad Rookie**

Escriba un programa de NumPy  que calcule la multiplicacion de dos matrices dadas

In [ ]:
#Desarrolle aqui su ejercicio


De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("matriz original:")
print(p)
print(q)
result1 = np.dot(p, q)
print("Resultado")
print(result1)

--->

**Ejercicio 4: Dificultad Rookie**

Escriba un programa de NumPy  que calcule el determinante de una matriz cuadrada dada

In [ ]:
#Desarrolle aqui su ejercicio


De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

import numpy as np
from numpy import linalg as LA
a = np.array([[1, 0], [1, 2]])
print("Original 2-d array")
print(a)
print("Determinant de un array 2-D ")
print(np.linalg.det(a))

--->

**Ejercicio 5: Dificultad Rookie**

Escriba un programa de NumPy programa que calcule la inversa de una matriz dada

In [ ]:
#Desarrolle aqui su ejercicio


De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

import numpy as np
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result =  np.linalg.inv(m)
print("Inversa de la  matriz:")
print(result)

--->

**Ejercicio 6: Dificultad Hero**

Escriba un programa de NumPy que convierta un array de tipo entero a uno de tipo flotante

In [ ]:
#Desarrolle aqui su ejercicio


De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

import numpy as np
a = [1, 2, 3, 4]
print("Array entero")
print(a)
x = np.asfarray(a)
print("Array convertido  a float type:")
print(x)
--->

**Ejercicio 7: Dificultad Hero**

Escriba un programa de NumPy que  a grados centigrados valores ingresados en grados  Fahrenheit. Los grados centigrados deben almacenarse en un numpy array

In [ ]:
#Desarrolle aqui su ejercicio


De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

import numpy as np
fahrenheit_values = [0, 12, 45.21, 34, 99.91]
F = np.array(fahrenheit_values)
print("Valores en:")
print(F)
print("Valores en  Centigrados:") 
print(5*F/9 - 5*32/9)
--->

**Ejercicio 7: Dificultad Leyenda**

Escriba un programa de NumPy que  a grados centigrados valores ingresados en grados  Fahrenheit. Los grados centigrados deben almacenarse en un numpy array

In [ ]:
#Desarrolle aqui su ejercicio


De click **aquí** para ver la respuesta.

<!---
# No esperaba verte tan rápido aquí :(

import numpy as np
fahrenheit_values = [0, 12, 45.21, 34, 99.91]
F = np.array(fahrenheit_values)
print("Valores en:")
print(F)
print("Valores en  Centigrados:") 
print(5*F/9 - 5*32/9)
--->